name: tamara_gateway
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.9.0


 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^0.13.5
  webview_flutter: ^4.4.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
